import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

import { CITIES } from '../../src/data/cities';
import {
  ECONOMY_CONFIG_VERSION,
  MARKET_TICK_INTERVAL_MS,
} from '../../src/simulation/economyClock';

const catalog = CITIES.map((city) => ({
  id: city.id,
  products: Object.fromEntries(
    Object.entries(city.products).map(([productId, product]) => [
      productId,
      {
        basePrice: product.basePrice,
        targetStock: product.targetStock,
        consumptionPerDay: product.consumptionPerDay,
      },
    ]),
  ),
}));

const outputPath = resolve(
  __dirname,
  '..',
  'src',
  'generated',
  'canonicalInputs.ts',
);
mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(
  outputPath,
  [
    '/** AUTO-GENERATED by npm run sync:canonical. Do not edit manually. */',
    `export const ECONOMY_CONFIG_VERSION = ${ECONOMY_CONFIG_VERSION} as const;`,
    `export const MARKET_TICK_INTERVAL_MS = ${MARKET_TICK_INTERVAL_MS} as const;`,
    `export const CANONICAL_CITY_MARKET_CATALOG = ${JSON.stringify(catalog, null, 2)} as const;`,
    '',
  ].join('\n'),
  'utf8',
);

console.log('[global-economy-worker] canonical inputs synchronized', {
  configVersion: ECONOMY_CONFIG_VERSION,
  cities: catalog.length,
});
